name: CI

on:
  push:
    #branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu] # todo, add mac and windows ?
        jvm_version: [11] # todo, add other java version, 15 and 16?
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
      - run: scala --version
      ## Sbt part
      - name: Setup Scala and JDK
        with:
          java-version: adopt@1.${{ matrix.jvm_version }}
        uses: olafurpg/setup-scala@v11
      - name: Sbt run tests
        shell: bash # for windows
        run: sbt test
      - name: Clean Sbt data
        run: sbt clean cleanFiles
      ## Gradle part
      - name: Gradle run tests
        run: ./gradlew build
    ## From https://github.com/AlchemistSimulator/Alchemist/blob/master/.github/workflows/build-and-deploy.yml

  Build-Success:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - shell: bash
        run: touch ok

  CI-Complete:
    needs: Build-Success
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: success
      - shell: bash
        run: '[ -f ok ]'
