name: CI

on:
  push:
    branches: [ master, develop ]
    tags: v*
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  Build-and-Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu] # todo, add mac and windows ?
        jvm_version: [11,16] # todo, add other java versions?
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala and JDK
        with:
          java-version: adopt@1.${{ matrix.jvm_version }}
        uses: olafurpg/setup-scala@v11
      - name: Sbt run tests
        shell: bash # for windows
        run: sbt +test

  Release:
    runs-on: ubuntu-latest
    needs: [Build-and-Test]
    #if: startsWith(github.ref, 'refs/tags/v') # run only for tagged commits
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: liberica@1.11.0
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASS }}
          PGP_PASSWORD: ${{ secrets.PGP_PASS }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
