name: CI

on:
  push:
    #branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos] # todo, add mac and windows
        jvm_version: [11, 15, 16] # todo, add other java version
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jvm_version }}
          distribution: 'adopt'
      ## Sbt part
      - name: Sbt run tests
        run: sbt test
      - name: Clean Sbt data
        run: sbt clean
      ## Gradle part
      - name: Gradle run tests
        run: ./gradlew build
    ## From https://github.com/AlchemistSimulator/Alchemist/blob/master/.github/workflows/build-and-deploy.yml

  Build-Success:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - shell: bash
        run: touch ok

  CI-Complete:
    needs: Build-Success
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: success
      - shell: bash
        run: '[ -f ok ]'